name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fgfg
      id: fgfg
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: fgfg
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 32
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FGFG_RESULTS: "${{steps.fgfg.outputs.result}}"
      with:
        runners: fgfg
